import type { NextPage } from "next";
import { GetStaticProps } from "next";
import { InferGetStaticPropsType } from "next";
import Head from "next/head";

// Components
import List from "../components/Games/List";

// WS
import commWS from "../interface/interface_ws";

const Home: NextPage = (props: InferGetStaticPropsType<typeof getStaticProps>) => {
      return (
            <div>
                  <Head>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                        <title>Ignite</title>
                  </Head>

                  <List classification="Games" currentGames={props.currentGames} />
            </div>
      );
};

export const getStaticProps: GetStaticProps = async () => {
      const result = await commWS.current_games();

      interface Game {
            id: number;
      }

      return {
            props: {
                  currentGames: result,
            },
      };
};

export default Home;
